repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: no-commit-to-branch
    args: [--branch, master]
  - id: trailing-whitespace
  - id: end-of-file-fixer

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v1.2.0
  hooks:
  - id: conventional-pre-commit
    stages: [commit-msg]

- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.17
  hooks:
  - id: terraform-fmt

- repo: https://github.com/bridgecrewio/checkov.git
  rev: 2.0.1050
  hooks:
  - id: checkov
    args: [--skip-path, src, --quiet]