repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: no-commit-to-branch
    args: [--branch, master]
  - id: trailing-whitespace
  - id: end-of-file-fixer

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v1.2.0
  hooks:
  - id: conventional-pre-commit
    stages: [commit-msg]
