name: "semver-tag-release"
description: "Creates a semver release/tag on push to master"

runs:
  using: "composite"
  steps:

      - name: Automated Version Bump
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.BYPASS }}
        with:
          skip-tag: 'false'
